import { initialState } from '../state';
import type { BuilderState, Beat, CinematographyBrief } from '../state';

const PH = '/_preview-placeholder.png';

const MOCK_BEATS: Beat[] = [
  { index: 0, archetype: 'open',        name: 'First light',          visual: 'Soft morning light streaming through a window onto a sleeping dog.',         caption: 'From the very first day.',              spokenOrTitle: 'From the very first day.',       lengthSeconds: 15 },
  { index: 1, archetype: 'memory',      name: 'The favourite spot',   visual: 'Biscuit curled up on the corner of the sofa, eyes half-closed.',              caption: 'A spot that was only theirs.',          spokenOrTitle: '',                               lengthSeconds: 15 },
  { index: 2, archetype: 'connection',  name: 'Walk in the park',     visual: 'A golden-hour stroll through autumn leaves, leash tugging forward.',          caption: 'Every walk felt like an adventure.',    spokenOrTitle: '',                               lengthSeconds: 15 },
  { index: 3, archetype: 'memory',      name: 'The look they gave',   visual: 'Close-up of warm brown eyes looking directly into the camera with love.',     caption: 'That look that said everything.',       spokenOrTitle: '',                               lengthSeconds: 15 },
  { index: 4, archetype: 'connection',  name: 'Playtime',             visual: 'Biscuit leaping for a ball in a sunlit garden, mid-air joy.',                 caption: 'Pure joy, every single time.',          spokenOrTitle: '',                               lengthSeconds: 15 },
  { index: 5, archetype: 'ceremonial',  name: 'The quiet evenings',   visual: 'Biscuit resting at feet by a fireplace, warm amber glow.',                   caption: 'Together, every evening.',              spokenOrTitle: '',                               lengthSeconds: 15 },
  { index: 6, archetype: 'release',     name: 'Goodbye, old friend',  visual: 'A paw resting gently on a human hand, soft light.',                          caption: 'You are not gone, only changed.',       spokenOrTitle: 'You are not gone, only changed.', lengthSeconds: 15 },
  { index: 7, archetype: 'close',       name: 'Forever in our hearts','visual': 'Silhouette of a dog at sunset, running free across an open meadow.',       caption: 'Forever loved.',                        spokenOrTitle: 'Forever loved.',                 lengthSeconds: 15 },
];

const MOCK_BRIEFS: CinematographyBrief[] = MOCK_BEATS.map((b, i) => ({
  beatIndex: b.index,
  lensMm:          ([50, 85, 35, 85, 35, 50, 105, 24] as const)[i],
  lensCharacter:   (['standard', 'portrait', 'standard', 'portrait', 'standard', 'standard', 'compression', 'wide_establishing'] as const)[i],
  cameraMove:      (['slow_push', 'locked_off', 'slow_pan_R', 'slow_push', 'slow_pull', 'locked_off', 'slow_pull', 'slow_rise'] as const)[i],
  moveIntensity:   'barely_perceptible',
  subjectMotion:   (['breath_only', 'loop_idle', 'loop_action', 'breath_only', 'loop_action', 'breath_only', 'locked', 'loop_action'] as const)[i],
  lightingMotion:  (['drifting_sunbeam', 'static', 'leaf_dapple_breeze', 'static', 'drifting_sunbeam', 'candle_flicker', 'static', 'drifting_sunbeam'] as const)[i],
  dofBehavior:     (['rack_to_subject', 'locked_shallow', 'locked_deep', 'locked_shallow', 'locked_deep', 'locked_shallow', 'rack_to_subject', 'locked_deep'] as const)[i],
  shotStructure:   'single_sustained',
  ambientAudio:    (['birdsong', 'silence', 'wind_grass', 'silence', 'birdsong', 'hearth_crackle', 'soft_rain', 'wind_grass'] as const)[i],
  audioIntensity:  'bed_only',
}));

const MOCK_BEAT_VIDEOS: Record<number, string> = Object.fromEntries(MOCK_BEATS.map(b => [b.index, PH]));
const MOCK_STORYBOARD: Record<number, string> = Object.fromEntries(MOCK_BEATS.map(b => [b.index, PH]));
const MOCK_CAPTION_CARDS: Record<number, string> = Object.fromEntries(MOCK_BEATS.map(b => [b.index, PH]));
const MOCK_CAPTION_OVERLAYS: Record<number, string> = Object.fromEntries(MOCK_BEATS.map(b => [b.index, PH]));

export function buildMockState(): BuilderState {
  return {
    ...initialState,
    returningUser: false,
    petName: 'Biscuit',
    petNamePronunciation: 'BIS-kit',
    gender: 'male',
    petProfile: {
      species: 'Dog',
      speciesConfidence: 'high',
      breedGuess: 'Golden Retriever',
      breedConfidence: 'high',
      coatDescription: 'Golden wavy',
      coatConfidence: 'high',
      ageRange: 'adult',
      ageConfidence: 'high',
      bodyType: 'large',
      observedSetting: 'A bright living room with soft afternoon light.',
      observedMoment: 'Resting comfortably, looking at the camera.',
      visionFailed: false,
    },
    petPhotos: [],
    memoryPromptType: 'morning',
    memoryPromptAnswer: 'would always greet me at the door every single morning without fail',
    relationship: 'always_mine',
    traits: ['gentle', 'playful', 'loyal'],
    favorites: ['long walks', 'belly rubs', 'squeaky toys'],
    creatorName: 'The Johnson Family',
    years: '2010–2024',
    yearsIncluded: true,
    characterSheetUrl: PH,
    characterSheetApproved: true,
    characterSheetRefinements: [],
    beatCount: 8,
    targetMinutes: 2,
    aspectRatio: '9:16',
    pickType: 'curated',
    curatorsPick: 'classic_send_off',
    format: 'send_off',
    themeCategory: 'healing_and_peace',
    theme: 'rainbow_bridge',
    style: 'cinematic_realism',
    combinationPreviewUrl: PH,
    beatSheet: MOCK_BEATS,
    beatSheetApproved: true,
    captionContainer: 'cinematic_lower_third',
    storyboardApproved: true,
    storyboardRerollRequests: [],
    storyboardImages: MOCK_STORYBOARD,
    beatVideos: MOCK_BEAT_VIDEOS,
    captionCardImages: MOCK_CAPTION_CARDS,
    captionOverlayImages: MOCK_CAPTION_OVERLAYS,
    burnedBeatVideos: {},
    assembledVideoUrl: PH,
    musicBedUrl: PH,
    musicBedDurationMs: 120000,
    narrationUrl: PH,
    narrationDurationMs: 110000,
    narrationScript: 'From the very first day, Biscuit was more than a pet. He was family.',
    narrationTimestamps: [
      { word: 'From',    startMs: 0,    endMs: 300  },
      { word: 'the',     startMs: 310,  endMs: 450  },
      { word: 'very',    startMs: 460,  endMs: 650  },
      { word: 'first',   startMs: 660,  endMs: 900  },
      { word: 'day',     startMs: 910,  endMs: 1100 },
      { word: 'Biscuit', startMs: 1200, endMs: 1550 },
      { word: 'was',     startMs: 1560, endMs: 1700 },
      { word: 'family',  startMs: 1750, endMs: 2100 },
    ],
    words: {
      opening: 'simple',
      openingCustom: ['', ''],
      closing: 'gratitude_simple_farewell',
      closingCustom: '',
      captions: MOCK_BEATS.slice(0, 3).map(b => ({ beatIndex: b.index, text: b.caption })),
      music: 'soft_piano_01',
      musicMode: 'preset',
      musicPrompt: 'Gentle instrumental memorial score for Biscuit with soft piano and warm strings.',
      musicStyle: 'soft piano, warm strings, gentle cinematic memorial score',
      musicTitle: 'For Biscuit',
      musicLyrics: '',
      musicProvider: 'suno',
      musicApproved: true,
      musicGenerationStatus: 'ready',
      musicGenerationError: '',
      musicVariants: [{ url: PH, durationMs: 120000, title: 'For Biscuit' }],
      narration: 'off',
      narrationLetter: [],
      subtitles: true,
      reviewed: true,
    },
    cardText: {
      opening: 'From the very first day.',
      closing: 'Forever loved, forever missed.',
    },
    cardPreviewImages: {
      opening: PH,
      closing: PH,
      caption: PH,
    },
    cardPreviewApproved: true,
    typographyLocked: 'cinematic_lower_third',
    dpStyle: 'none',
    cinematographyBriefs: MOCK_BRIEFS,
    engineAdjustments: ['Adjusted lens for beat 0: switched from 85mm to 50mm for a wider establishing feel.'],
    cinematographyApproved: true,
    gateNotes: {
      characterSheet: '',
      storyboard: '',
      cinematography: '',
      cardPreview: '',
    },
    generationComplete: true,
    eulogyRequested: false,
  };
}
