/**
 * Generate a fresh VAPID keypair for Web Push.
 *
 * Run once per environment (dev / staging / prod). Paste the printed values
 * into the matching `.env.local` / hosted env, then restart the worker so it
 * picks up the new keys.
 *
 * Re-running this script invalidates every existing push subscription
 * because subscriptions are tied to the public key the browser saw at
 * subscribe time. Don't rotate keys casually.
 */
import webpush from 'web-push';

const { publicKey, privateKey } = webpush.generateVAPIDKeys();

const lines = [
  '# Generated by `npm run vapid:generate` — paste into .env.local',
  `VAPID_PUBLIC_KEY=${publicKey}`,
  `VAPID_PRIVATE_KEY=${privateKey}`,
  '# Subject must be a mailto: URL or your origin (https://...).',
  'VAPID_SUBJECT=mailto:admin@peterna.com',
];
for (const line of lines) console.log(line);
